Repository AY2324S1-CS2103T-W09-3/tp, pull requests merged in 2023-11, with the labels that each got.

#108 Update User Guide
  docs/UserGuide.md
Labels: type.documentation, priority.high

#109 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.documentation, priority.high

#110 update UG
  docs/UserGuide.md
Labels: type.documentation, priority.high

#111 Update GUI and fix view bug
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ViewAvailableCommand.java
  src/main/java/seedu/address/model/ClinicAssistant.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/timeslots/UniqueTimeSlotList.java
  src/main/java/seedu/address/ui/TimeSlotCard.java
  src/main/java/seedu/address/ui/TimeSlotListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TimeSlotCard.fxml
  src/main/resources/view/TimeSlotListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.story, priority.high

#166 fix appointment bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ClinicAssistant.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/doctor/UniqueDoctorList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/timeslots/UniqueTimeslotList.java
  src/main/java/seedu/address/storage/JsonSerializableClinicAssistant.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
Labels: type.bug, type.enhancement, priority.high

#170 Add patient and doc bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/doctor/Doctor.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.bug, priority.mid

#112 Add tests for AddAppointment
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.mid

#187 Pin Ren PPP
  docs/team/tohpinren.md
Labels: type.documentation, priority.mid

#190 Ug update: appt & edit_appt
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentsCommand.java
Labels: type.documentation

#191 update command summary
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.documentation

#192 add how to use and table of contents
  docs/UserGuide.md
Labels: type.documentation, priority.high

#196 Update UG: Target audience, list_appt, find_appt
  docs/UserGuide.md
Labels: type.documentation, priority.mid

#185 Update UG
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.documentation

#218 Edit dg
  docs/DeveloperGuide.md
Labels: type.documentation, priority.mid

#226 Update UG, added graphics
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditCommandParserSeqDiagram.puml
  docs/diagrams/EditCommandSeqDiagram.puml
  docs/images/add_doc.png
  docs/images/add_doc_err1.png
  docs/images/del.png
  docs/images/del_fail1.png
  docs/images/del_fail2.png
  docs/images/edit_fail.png
  docs/images/edit_success.png
  docs/images/find.png
  docs/images/view.png
  docs/images/view_err1.png
  docs/images/view_err2.png
  docs/img.png
  docs/team/yezkez10.md
Labels: type.documentation

#239 Update ppp
  docs/AboutUs.md
  docs/team/tohpinren.md
Labels: type.documentation
