Repository AY2324S1-CS2103T-W09-3/tp, pull requests merged in 2023-10, with the labels that each got.

#21 Update UG delete appointment
  docs/UserGuide.md
Labels: type.documentation, priority.mid

#27 Update User Guide small change
  docs/UserGuide.md
Labels: type.documentation, priority.mid

#26 Add Project Portfolio Page
  docs/AboutUs.md
  docs/team/bryan-goh.md
Labels: type.documentation, priority.mid

#30 Update readme
  README.md
  docs/UserGuide.md
  docs/images/AB3Ui.png
  docs/images/Ui.png
  docs/index.md
Labels: type.documentation, priority.mid

#31 Add documentation for 'add' feature in user guide
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/bryan-goh.md
  docs/team/johndoe.md
  docs/team/yezkez10.md
Labels: type.documentation, priority.high

#34 Fix ug and website
  README.md
  docs/UserGuide.md
Labels: type.documentation, priority.mid

#48 Edit User Guide
  docs/UserGuide.md
Labels: type.documentation, priority.low

#41 Modify DeleteCommand
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.enhancement

#52 Delete appointment
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AppointmentAddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high

#56 Bug fix
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
Labels: type.bug, priority.high

#57 edit appointment implementation
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AppointmentAddCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.enhancement, priority.high

#63 fix Patient storage parsing issue
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.bug, priority.high

#69 Fix parsing storage to FE
  src/main/java/seedu/address/model/ClinicAssistant.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableClinicAssistant.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
Labels: type.enhancement, priority.high

#74 fix edit appointment FE
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/model/ClinicAssistant.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonSerializableClinicAssistant.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.bug, priority.high

#75 Add new fields to parse in EditCommandParser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: WIP

#64 Create branch to resolve test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Ethnicity.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.bug, priority.mid, WIP

#86 Change edit and delete appointment to by index of appointments only and update delete
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentParser.java
  src/main/java/seedu/address/logic/parser/ClinicAssistantParser.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/model/ClinicAssistant.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyClinicAssistant.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/ClinicAssistantParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/ClinicAssistantTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.enhancement, priority.mid

#94 Fix edit and delete appointment testcases
  bin/test/seedu/address/logic/commands/FindAppointmentCommandTest.class
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableClinicAssistant.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ClinicAssistantParserTest.java
  src/test/java/seedu/address/model/ClinicAssistantTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonClinicAssistantStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableClinicAssistantTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: priority.high

#99 Update dg
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#98 Add Doctors to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctor.puml
Labels: priority.mid

#78 List appt sort by dates
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
Labels: type.enhancement, priority.mid

#107 Enable assertions
  build.gradle
Labels: priority.mid

#93 Add find by nric feature
  src/main/java/seedu/address/logic/commands/FindByNricCommand.java
  src/main/java/seedu/address/logic/parser/ClinicAssistantParser.java
  src/main/java/seedu/address/logic/parser/FindByNricCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/NricContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindByNricCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByNricCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NricContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high
